apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-test
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"